- name: Install prerequisites for Node.js
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
  become: true

- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download NodeSource GPG key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /tmp/nodesource-repo.gpg.key
    mode: '0644'
  become: true

- name: Add NodeSource GPG key
  ansible.builtin.shell:
    cmd: cat /tmp/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
    creates: /etc/apt/keyrings/nodesource.gpg
  become: true

- name: Add NodeSource repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main"
    state: present
    filename: nodesource
  become: true

- name: Install Node.js 22
  ansible.builtin.apt:
    name:
      - nodejs
    update_cache: true
  become: true

- name: Install global npm packages
  community.general.npm:
    name: '{{ item }}'
    global: true
  loop:
    - typescript
    - ts-node
  become: true
